[env:esp32dev]
; LOCK DELLA PIATTAFORMA: Previene rotture causate da rolling releases
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; === PRE-BUILD SCRIPT ===
extra_scripts = pre:generate_secrets.py


; OTTIMIZZAZIONI COMPILATORE: Debug level 1 (Solo Errori) per evitare colli di bottiglia seriali
build_flags =
    -D CORE_DEBUG_LEVEL=1

; LOCK DELLE LIBRERIE: Nessun bloatware, solo i driver atomici richiesti
lib_deps =
    adafruit/RTClib @ ^2.1.3
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit FRAM I2C @ ^2.0.3
    bblanchon/ArduinoJson @ ^6.21.3
    SPI
    Wire
